version: '3.5'
services:
    oic:
        restart: always
        container_name: oic
        build:
            context: oic-app
            dockerfile: Dockerfile
        ports:
            - 5005:3000
        links:
            - mongodb
        depends_on:
            - mongodb
    