version: '3.5'
services:
    oic:
        restart: always
        container_name: oic
        build:
            context: oic-app
            dockerfile: Dockerfile
        ports:
        - 3000:3005
    